configfile: "config/config.yaml"

rule all:
    input: 
        test1="output/test1.txt",
        test2="output/test2.txt"

rule test1:
    output: 
        test1="output/test1.txt"
    conda: "envs/DEEPLABCUT.yaml"
    shell:
        """
        touch {output.test1}
        echo "Done!"
        """

rule test2:
    output: 
        test2="output/test2.txt"
    conda: "simba"
    shell:
        """
        touch {output.test2}
        echo "Done!"
        """


